version: '3.4'

services:
  signalrwithmqtt_back:
    image: ${DOCKER_REGISTRY-}signalrwithmqttback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5050:80
        - 5051:443

